### ISSUE TITLE
Dragging the bubble view its movement is not as smooth as facebook chat heads

### ISSUE THREAD

**Issue by tuhin10** [Cleveroad/MusicBobber#11]
While dragging the bubble view its movement is not as smooth as facebook chat heads or BuMp player. Is there any way to make the movement much more natural??

**Comment by Iojjj** [comment]
We'll put this to the list of enhancements for future release. 

You can try to play with [TouchManger](https://github.com/Cleveroad/MusicBobber/blob/master/audiowidget/src/main/java/com/cleveroad/audiowidget/TouchManager.java) and it's [VelocityAnimator](https://github.com/Cleveroad/MusicBobber/blob/master/audiowidget/src/main/java/com/cleveroad/audiowidget/TouchManager.java#L300). If you will make movement smoother, you can send us a pull request into **develop** branch.

**Comment by Iojjj** [comment]
Widget's movement in v.1.0.0 became much smoother. Give it a try.
