### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by luzhzhsoft** [Cleveroad/MusicBobber#12]
```
I find a little bug in your code.
```

when you use windowManager.updateViewLayout(playPauseButton,params);maybe have an erro:

java.lang.IllegalArgumentException: View=com.cleveroad.audiowidget.PlayPauseButton{42fbbb50 V.ED.... ......I. 0,0-360,360} not attached to window manager

private void updatePlayPauseButtonPosition() {
        WindowManager.LayoutParams widgetParams = (WindowManager.LayoutParams) expandCollapseWidget.getLayoutParams();
        WindowManager.LayoutParams params = (WindowManager.LayoutParams) playPauseButton.getLayoutParams();
        if (expandCollapseWidget.expandDirection() == ExpandCollapseWidget.DIRECTION_RIGHT) {
            params.x = (int) (widgetParams.x - radius);
        } else {
            params.x = (int) (widgetParams.x + widgetWidth - widgetHeight - radius);
        }
        params.y = widgetParams.y;
        windowManager.updateViewLayout(playPauseButton, params);
        if (onWidgetStateChangedListener != null) {
            onWidgetStateChangedListener.onWidgetPositionChanged((int) (params.x + widgetHeight), (int) (params.y + widgetHeight));
        }
    }

**Comment by Iojjj** [comment]
fixed in 0.9.2. Check [migration guide](https://github.com/Cleveroad/MusicBobber#migration-from-v091-to-v092)
