### ISSUE TITLE
Seekbar Issue

### ISSUE THREAD

**Issue by sajorahasan** [Cleveroad/MusicBobber#17]
Hi Guys,

We are trying to use the bobber in one of our android app and it has been great. The only part we need is a seekbar using which we can forward or move backward in the song.

Is there any way to achieve that or is there any enhancement you are thinking about? Can you guide us with that if there is any way to do that?

Regards
Hasan Sajora

**Comment by Iojjj** [comment]
Hi @sajorahasan,

we are not planning to add any new feature for now. So you need to implement it on your own. It would be great to receive a PR for such functionality.

Currently `PlayPauseButton` class draws button as well as playback position. It's your starting point. You can modify the way progress drawn there and add touch handlers to allow user to change track position. If you want to add seekbar to expanded view, then `ExpandCollapseWidget` should be modified.

**Comment by sajorahasan** [comment]
Thanks for help
Really appreciate that.
