### ISSUE TITLE
Change play/pause button status

### ISSUE THREAD

**Issue by Saad-Mahmud** [Cleveroad/MusicBobber#18]
When i press my media player button from play to pause or pause to play i also want to change the widget play/pause button. How to do that?

**Comment by cinder92** [comment]
same issue here 👍

**Comment by VadimHalimendikCr** [comment]
Hey.
Sorry for the late reply, but we did not have time to check the issues in our libraries.

AudioWidget implement Controller methods and has method to get widget controller named controller(). Controller can set start, pause and stop playbackState. So you can just use   audioWidget.controller().start() for set startState and  audioWidget.controller().pause() for pause
