### ISSUE TITLE
Android 8.0 Oreo Permission (permission denied for window type 2002)

### ISSUE THREAD

**Issue by halit4603** [Cleveroad/MusicBobber#20]
I really do not know how to use this library in Android 8.0. "<uses-permission android: name =" android.permission.SYSTEM_ALERT_WINDOW "/>" Permission to crunch an app that does not work. Any help in this regard will be appreciated.

**Comment by halit4603** [comment]
I found the answer myself. I first made the following change to the AudioWidget.java file to import the library as a folder, not as dependencies, and then to work seamlessly with both oreo and kitkat versions. I hope someone works.

private void show(View view, int left, int top) {

        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            WindowManager.LayoutParams params = new WindowManager.LayoutParams(
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.TYPE_PHONE,
                    WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
                            | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
                            | WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH
                            | WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
                    PixelFormat.TRANSLUCENT);

            params.gravity = Gravity.START | Gravity.TOP;
            params.x = left;
            params.y = top;
            windowManager.addView(view, params);

        } else {
            WindowManager.LayoutParams params = new WindowManager.LayoutParams(
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.WRAP_CONTENT,
                    WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,
                    WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
                            | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
                            | WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH
                            | WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
                    PixelFormat.TRANSLUCENT);


            params.gravity = Gravity.START | Gravity.TOP;
            params.x = left;
            params.y = top;
            windowManager.addView(view, params);
        }
    }

**Comment by akashk2512** [comment]
Cool it's working.

**Comment by VadimHalimendikCr** [comment]
In version 1.0.1 of the library this was fixed.

**Comment by hiralpatel** [comment]
**Cool its work for me!!!**
Thanks for sharing.

**Comment by Arya-pd** [comment]
can anyone tell me steps how to do this
