### ISSUE TITLE
 Great, I ask where can I download

### ISSUE THREAD

**Issue by guoyoujin** [Cleveroad/MusicBobber#4]
Great, I ask where can I download

**Comment by Iojjj** [comment]
Hi there.

To include this widget into your project you need to add dependency in your `build.gradle` file:

``` gradle
compile 'com.cleveroad:audiowidget:0.9.0'
```

You can also pull the sources and use them.

**Comment by saikatharryc** [comment]
HI @Iojjj  is it compatible for hybrid development? like as with Cordova?

**Comment by Iojjj** [comment]
Hi @saikatharryc ,

This is a native android component, so if you want to use it in hybrid apps, you need to include this lib and call it from javascript with [javascript interface](https://developer.android.com/guide/webapps/webview.html#BindingJavaScript).
