### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jordyamc** [Cleveroad/MusicBobber#7]
I suggest to add onClick/onLongClick listeners to albumCover, or on Disk-like image to collapse

Or custom actions

**Comment by Iojjj** [comment]
[AudioWidget.OnControlsClickListener](https://github.com/Cleveroad/MusicBobber/blob/master/audiowidget/src/main/java/com/cleveroad/audiowidget/AudioWidget.java#L1146-L1173) already has two methods for this: **onPlaylistClicked** and **onAlbumClicked**. If you want to override collapse behavior on playlist click, just return false and do whatever you want.

We will think about adding onLongClick listeners for this buttons.

**Comment by Iojjj** [comment]
Added long click listeners for expanded widget buttons in v.0.9.2. Check [migration guide](https://github.com/Cleveroad/MusicBobber#migration-from-v091-to-v092)
