### ISSUE TITLE
Add album cover as background in the circular mini state

### ISSUE THREAD

**Issue by tuhin10** [Cleveroad/MusicBobber#8]
![screenshot_2016-04-30-01-45-58](https://cloud.githubusercontent.com/assets/11805182/14930749/047bee30-0e84-11e6-9daa-4ad677632283.png)
Add the album cover as the background of the playpause button

**Comment by Iojjj** [comment]
We'll discuss it and inform you if this will be added to list of enhancements.

**Comment by Iojjj** [comment]
Album cover for play/pause button was added in v.1.0.0.
