### ISSUE TITLE
Enhancement: Bubble remover view expands while dropping the bubble

### ISSUE THREAD

**Issue by tuhin10** [Cleveroad/MusicBobber#9]
It will be nice if the size of the bubble remover view expands while dropping the bubble just like facebook chat head works

![screenshot_2016-04-30-01-45-25](https://cloud.githubusercontent.com/assets/11805182/14931157/d9785a7c-0e86-11e6-9c32-c0eb12b0eff8.png)

**Comment by Iojjj** [comment]
We'll put this to the list of enhancements for future release.

**Comment by Iojjj** [comment]
Check [migration guide](https://github.com/Cleveroad/MusicBobber#migration-from-v091-to-v092) for v.0.9.2
